# Generated by Django 5.1.1 on 2024-09-16 18:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('item_type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('consumable', 'Consumable'), ('misc', 'Miscellaneous')], max_length=20)),
                ('weight', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('char_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=30)),
                ('char_class', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('campaign', models.CharField(max_length=100)),
                ('strength', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('dexterity', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('constitution', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('intelligence', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('wisdom', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('charisma', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('athletics', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('acrobatics', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('stealth', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('sleight_of_hand', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('arcana', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('history', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('investigation', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('nature', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('religion', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('insight', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('animal_handling', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('medicine', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('perception', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('survival', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('performance', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('deception', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('intimidation', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('persuasion', models.CharField(choices=[('not_proficient', 'Not proficient'), ('proficient', 'Proficient'), ('expert', 'Expert')], default='not_proficient', max_length=20)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('speed', models.FloatField(default=9.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.player')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='char_sheet.inventoryitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='char_sheet.player')),
            ],
            options={
                'unique_together': {('player', 'item')},
            },
        ),
    ]
